/// ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====>  			Pourc1	Pourc2	Category1						Category2							Category3    			// configure categories in ZombiesCategories.c file
																																													/// (ex: 0.80,	0.95 => 80% chance to spawn zombie in 1st categorie, 15% in 2nd categorie and 5% in 3rd categorie)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_000_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		Empty,							Empty,								Empty); 						// No Zombies (don't modify this one)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_001_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80,	1,		Zombie_Type_Countryside_Weak,	Zombie_Type_Countryside_Strong,		Empty);							// 1 CountrySide : Outside any dynamic zones
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_010_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80, 	1,		Zombie_Type_SmallTown_Weak,		Zombie_Type_SmallTown_Strong,		Empty); 						// 10 Small Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_020_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80,	1,		Zombie_Type_MediumTown_Weak,	Zombie_Type_MediumTown_Strong,		Empty); 						// 20 Medium Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_030_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.70,	0.90,	Zombie_Type_BigTown_Slow,		Zombie_Type_BigTown_Weak,			Zombie_Type_BigTown_Strong);	// 30 Big Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_040_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.70,  1,		Zombie_Type_Industrial_Strong,	Zombie_Type_NBC_Weak,				Empty);							// 40 Indus + NBC
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_050_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80,  1,		Zombie_Type_Industrial_Weak,	Zombie_Type_Industrial_Strong,		Empty); 						// 50 Industrial
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_060_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80,  1,		Zombie_Type_MilitaryDyna_Weak,	Zombie_Type_MilitaryDyna_Strong,	Empty); 						// 60 Military (Dynamic Spawn)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_070_ZombiesCategories         = new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); 						// 70 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_071_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,  	1,		Empty,							Empty,								Empty); 						// 71 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_072_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); 						// 72 

ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_101_MilitaryTentesCategories  = new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80, 	1,		Zombie_Type_Hospital_Weak,		Zombie_Type_Hospital_Medium,		Empty); 						// 101 Medic (Healthcare)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_102_CastelCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.60,	0.85,	Zombie_Type_Hospital_Weak,		Zombie_Type_Hospital_Medium,		Zombie_Type_Hospital_Strong); 	// 102 Medic (Hospital)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_103_ChurchCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Priest,				Empty,								Empty); 						// 103 // Church (quantity managed by the json)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_104_ComicoCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.70, 	0.80,	Zombie_Type_Police_Weak,		Zombie_Type_Police_Strong,			Zombie_Type_PrisonPrisoner); 	// 104 Police
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_105_DispensaryCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.95,	1,		Zombie_Type_GazStation_Weak,	Zombie_Type_GazStation_Strong,		Empty); 						// 108 GasStation
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_106_FireStationCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.90,	1,		Zombie_Type_FireFighter,		Zombie_Type_NBC_Weak,				Empty);							// 106 FireStation
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_107_FisherCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80,	0.95,	Zombie_Type_SmallCamp_Weak,		Zombie_Type_Hospital_Weak,			Zombie_Type_NBC_Weak); 			// 107 Military + Medic (Low)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_108_GazStationCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80,	0.95,	Zombie_Type_MediumCamp_Weak,	Zombie_Type_Hospital_Medium,		Zombie_Type_NBC_Strong); 		// 108 Military + Medic (Hight) 						// 108 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_109_HolidayCampCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.70,  0.80,	Zombie_Type_MediumCamp_Weak,	Zombie_Type_MediumCamp_Strong,		Zombie_Type_Industrial_Weak); 	// 109 Military + Indus (Low) 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_110_HospitalCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.50,  0.80,	Zombie_Type_BigCamp_Weak,		Zombie_Type_MediumCamp_Strong,		Zombie_Type_Industrial_Strong); // 110 Military + Indus (Hight)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_111_IndustrialCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.70,	0.80,	Zombie_Type_BigCamp_Weak,		Zombie_Type_BigCamp_Strong,			Zombie_Type_NBC_Strong); 		// 111 Military + NBC  
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_112_TownHallCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80, 	1,		Zombie_Type_SmallCamp_Weak,		Zombie_Type_SmallCamp_Strong,		Empty); 						// 112 Military Small Camp
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_113_PoliceStationCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80, 	1,		Zombie_Type_MediumCamp_Weak,	Zombie_Type_MediumCamp_Strong,		Empty); 						// 113 Military Medium Camp
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_114_PrisonCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.80, 	1,		Zombie_Type_BigCamp_Weak,		Zombie_Type_BigCamp_Strong,			Empty);							// 114 Military Big Camp
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_115_MilitaryBaseCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		Empty,							Empty,								Empty);							// 115 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_116_RiffyCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		Empty,							Empty,								Empty); 						// 116 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_117_SchoolCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,  	1,		Empty,							Empty,								Empty); 						// 117 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_118_ShopCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Butcher,			Empty,								Empty);	 						// 118 // Shop (quantity managed by the json)

/// Data groups you can tweak to add new configurations					/// Don't worry about variables name, look at the comment at the end of the line instead
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_090_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_091_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_092_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); //  
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_093_ZombiesCategories         = new Param5<float, float, TStringArray, TStringArray, TStringArray>    (1,		1,		Empty,Empty,Empty); // 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_094_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_095_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_096_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_097_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Spooky,				Empty,								Empty); 						// 97 Spooky (quantity managed by the json)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_098_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Santa,				Empty,								Empty); 						// 98 Zonta (quantity managed by the json)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_099_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.75,	1,		Zombie_Type_NBC_Weak,			Zombie_Type_NBC_Strong,				Empty); 						// 99 Toxic

// Don't add or delete lines, just use and modify the existing ones.
