/// ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====>  			Pour1	Pourc2	Category1						Category2							Category3    			// configure categories in ZombiesCategories.c file
																																													/// (ex : 0.80,	0.95 => 80% chance to spawn zombie in 1st categorie, 15% in 2nd categorie and 5% in 3rd categorie)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_000_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,  1,			Zombie_Type_AverageTown_Low,	Empty,							Empty); 			// 00 No Zombies (don't modify this one)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_001_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.99,	1,		Zombie_Type_Desert_Low,			Zombie_Type_Hunter,				Empty);				// 01 Desert
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_010_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.95,	0.99,	Zombie_Type_SmallTown_Low,		Zombie_Type_SmallTown_Hight,	Zombie_Type_Hunter);// 10 Small Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_020_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.90,	0.99,	Zombie_Type_AverageTown_Low,	Zombie_Type_AverageTown_Hight,	Zombie_Type_Hunter);// 20 Average Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_030_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.85,	0.99,	Zombie_Type_BigTown_Low,		Zombie_Type_BigTown_Hight,		Zombie_Type_Hunter);// 30 Big Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_040_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.30,	0.99,	Zombie_Type_Villa_Low,			Zombie_Type_Villa_Hight,		Zombie_Type_Hunter);// 40 Villa
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_050_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.95,	0.99,	Zombie_Type_Industrial_Low,		Zombie_Type_Industrial_Hight,	Zombie_Type_Hunter);// 50 Industrial
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_060_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.85,	0.99,	Zombie_Type_MilitaryeBase_Low,	Zombie_Type_MilitaryeBase_Hight,Zombie_Type_Hunter);// 60 Military
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_070_ZombiesCategories         = new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.90,	0.99,	Zombie_Type_GazStation_Low,		Zombie_Type_GazStation_Hight,	Zombie_Type_Hunter);// 70 GasStation
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_071_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.50,	1,		Zombie_Type_Medical_Low,		Zombie_Type_Medical_Hight,		Empty); 			// 71 Medical
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_072_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Police_Low,			Zombie_Type_Police_Hight,		Empty); 			// 72 PoliceStation

ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_101_MilitaryTentesCategories  = new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.5,	1,		Zombie_Type_Priest,				Zombie_Type_All,				Empty); 			// 101 Mosque
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_102_CastelCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 102 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_103_ChurchCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Priest,				Empty,							Empty); 			// 103 For automatic spawns near Minarets  (quantity managed by the json)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_104_ComicoCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 104 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_105_DispensaryCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 105 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_106_FireStationCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Bonfire,			Empty,							Empty); 			// 106 For automatic spawns near Bonfires
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_107_FisherCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 107 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_108_GazStationCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 108 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_109_HolidayCampCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 109 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_110_HospitalCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 110 Hospital 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_111_IndustrialCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 111 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_112_TownHallCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 112 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_113_PoliceStationCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 113 BigPoliceStation
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_114_PrisonCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 114 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_115_MilitaryBaseCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 115  
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_116_RiffyCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 116 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_117_SchoolCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 117 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_118_ShopCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Butcher,			Empty,							Empty);				// 118 For automatic spawns in Restaurants (quantity managed by the json)

/// Data groups you can tweak to add new configurations
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_090_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 90 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_091_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 91 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_092_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 92  
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_093_ZombiesCategories         = new Param5<float, float, TStringArray, TStringArray, TStringArray>    (1,		1,		Empty,Empty,Empty); // 93 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_094_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 94 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_095_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 95 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_096_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,Empty,Empty); // 96 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_097_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Spooky,				Empty,								Empty); 		// 97 Spooky (v1.19)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_098_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Santa,				Empty,								Empty); 		// 98 Zonta	(v1.15 update)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_099_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.75,	1,		Zombie_Type_NBC_Low,			Zombie_Type_NBC_Hight,				Empty); 		// 99 Toxic (v1.14 update)

// Don't add or delete lines, just use and modify the existing ones.
